Repository forcedotcom/source-deploy-retrieve, pull requests merged in 2021-07, with the labels that each got.

#373 chore: generated CHANGELOG for 3.1.1
  CHANGELOG.md
Labels: port:develop

#372 Wr/bot version
  src/registry/registry.json
Labels: port:develop

#382 Add BatchCalcJobDefinition to metadata registry
  src/registry/registry.json
Labels: cla:signed

#383 chore: enable EmailServicesFunction
  scripts/update-registry/typeOverride.json
  src/registry/registry.json
  src/resolve/metadataResolver.ts
Labels: port:develop

#385 chore: generated CHANGELOG for 4.0.0
  CHANGELOG.md
Labels: port:develop

#387 Port pr v4.0.0
  src/client/metadataApiDeploy.ts
  src/client/metadataApiRetrieve.ts
  src/client/metadataTransfer.ts
  src/client/types.ts
  src/collections/componentSet.ts
  src/convert/metadataConverter.ts
  src/registry/registry.json
  src/resolve/metadataResolver.ts
  test/client/metadataApiDeploy.test.ts
  test/client/metadataApiRetrieve.test.ts
  test/collections/componentSet.test.ts
  test/convert/convertContext.test.ts
  test/convert/metadataConverter.test.ts
  test/convert/transformers/decomposedMetadataTransformer.ts
  test/convert/transformers/metadataTransformerFactory.test.ts
  test/mock/client/transferOperations.ts
  test/mock/registry/index.ts
  test/mock/registry/mockRegistry.ts
  test/mock/registry/type-constants/decomposedConstants.ts
  test/mock/registry/type-constants/index.ts
  test/mock/registry/type-constants/reginaConstants.ts
  test/registry/registryAccess.test.ts
  test/resolve/adapters/baseSourceAdapter.ts
  test/resolve/adapters/decomposedSourceAdapter.ts
  test/resolve/adapters/sourceAdapterFactory.test.ts
  test/resolve/metadataResolver.test.ts
  test/resolve/sourceComponent.test.ts
Labels: cla:signed, port:develop

#389 chore: add CustomFieldTranslation to registry
  src/registry/registry.json
Labels: port:develop

#395 fix: add RunTestResult type
  src/client/types.ts
Labels: port:develop

#393 fix: add missing types from toolbelt to the best of my ability
  src/registry/registry.json
Labels: port:develop

#402 Revert "fix: add RunTestResult type"
  src/client/types.ts
Labels: port:develop

#403 Revert "chore: add CustomFieldTranslation to registry"
  src/registry/registry.json
Labels: port:develop

#404 Revert "fix: add missing types from toolbelt to the best of my ability"
  src/registry/registry.json
Labels: port:develop

#409 Changelog v4.0.1
  CHANGELOG.md
Labels: port:develop
