Repository forcedotcom/source-deploy-retrieve, pull requests merged in 2022-02, with the labels that each got.

#565 docs: fix broken refs in metadata doc
  contributing/metadata.md
Labels: documentation

#571 Component set from connection
  METADATA_SUPPORT.md
  src/client/types.ts
  src/collections/componentSet.ts
  src/collections/types.ts
  src/index.ts
  src/registry/index.ts
  src/registry/standardvalueset.ts
  src/registry/stdValueSetRegistry.json
  src/resolve/connectionResolver.ts
  src/resolve/index.ts
  test/collections/componentSet.test.ts
  test/resolve/connectionResolver.test.ts
  test/tsconfig.json
  tsconfig.json
Labels: cla:signed, feature

#572 rohitachar/ add new UiViewDefinition metadata type to registry
  METADATA_SUPPORT.md
  src/registry/metadataRegistry.json
Labels: cla:missing

#580 feat(metadata registry): adding flowtest type to metadata registry
  src/registry/metadataRegistry.json
Labels: cla:missing
