Repository forcedotcom/source-deploy-retrieve, pull requests merged in 2022-05, with the labels that each got.

#628 fix: resolveTypeFromStrictFolder for children of decomposed types wit…
  src/resolve/metadataResolver.ts
Labels: cla:signed

#619 fix: support file responses for metadata format deploys
  src/client/metadataApiDeploy.ts
Labels: type:bug

#635 Sm/qa 630
  METADATA_SUPPORT.md
  package.json
  src/registry/metadataRegistry.json
  src/resolve/connectionResolver.ts
  test/resolve/connectionResolver.test.ts
  yarn.lock
Labels: cla:signed

#634 docs: adds steps for updating registry and local setup rev@mshanemc
  contributing/metadata.md
Labels: cla:signed

#616 feat(metadata registry): adding BotTemplate to metadata registry
  src/registry/metadataRegistry.json
Labels: cla:signed, feature
