Repository forcedotcom/source-deploy-retrieve, pull requests merged in 2024-05, with the labels that each got.

#1301 feat: warn about .forceignore and the unpackaged folder
  src/resolve/forceIgnore.ts
Labels: enhancement, feature, type: feature

#1320 Add new datakit entity datakitobjectdependency
  src/registry/metadataRegistry.json
Labels: cla:signed

#1327 @W-15638748 | Changes to support EnblProgramTaskSubCategory and LearningItemType
  src/registry/metadataRegistry.json
Labels: cla:missing
